"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_bg2)\
$os\
$username\
[](bg:color_bg1 fg:color_bg2)\
$directory\
[](fg:color_bg1 bg:color_bg3)\
$git_branch\
$git_status\
[](fg:color_bg3 bg:color_bg1)\
$nix_shell\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_bg1 bg:color_bg2)\
$time\
[ ](fg:color_bg2)\
$line_break$character"""

palette = 'monochrome'

[palettes.monochrome]
color_fg0 = '#ffffff'
color_bg1 = '#2a2a2a'
color_bg2 = '#1a1a1a'
color_bg3 = '#3a3a3a'
color_pink = '#fe386e'

[os]
disabled = false
style = "bg:color_bg2 fg:color_fg0"

[os.symbols]
Linux = "󰌽"
NixOS = ""

[username]
show_always = true
style_user = "bg:color_bg2 fg:color_fg0"
style_root = "bg:color_bg2 fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_bg1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[nix_shell]
disabled = false
style = "fg:color_pink bg:color_bg1"
format = '[$state]($style)'
impure_msg = ' dev-shell '

[git_branch]
symbol = ""
style = "bg:color_bg3"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:color_pink bg:color_bg3"
format = '[$all_status$ahead_behind ]($style)'

[nodejs]
symbol = ""
style = "bg:color_bg1"
format = '[ $symbol $version ]($style)'

[c]
symbol = ""
style = "bg:color_bg1"
format = '[ $symbol $version ]($style)'

[rust]
symbol = ""
style = "bg:color_bg1"
format = '[ $symbol $version ]($style)'

[golang]
symbol = ""
style = "bg:color_bg1"
format = '[ $symbol $version ]($style)'

[php]
symbol = ""
style = "bg:color_bg1"
format = '[ $symbol $version ]($style)'

[java]
symbol = " "
style = "bg:color_bg1"
format = '[ $symbol $version ]($style)'

[kotlin]
symbol = ""
style = "bg:color_bg1"
format = '[ $symbol $version ]($style)'

[haskell]
symbol = ""
style = "bg:color_bg1"
format = '[ $symbol $version ]($style)'

[python]
symbol = ""
style = "bg:color_bg1"
format = '[ $symbol $version ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg2"
format = '[  $time ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[→](bold white)'
error_symbol = '[→](bold red)'
